### ISSUE TITLE
E_NOTICE - Undefined index: enabled

### ISSUE THREAD

**Issue by ohnonot** [Sommerregen/grav-plugin-smileys#9]
This is the error I get on page reload, simply trying smileys out with all default settings.
setting the plugin to `enabled: false` in user/config/plugins/smileys.yaml makes the error go away, but then of course the plugin doesn't do anything either.
My grav is up-to-date.
Am I missing something here?

relevant log entry:
```
[2016-12-10 12:19:29] grav.CRITICAL: Undefined index: enabled - Trace: #0 /path/to/grav/user/plugins/smileys/classes/Smileys.php(202): Whoops\Run->handleError(8, 'Undefined index...', '/path/to/grav...', 202, Array) #1 /path/to/grav/user/plugins/smileys/classes/Smileys.php(80): Grav\Plugin\Smileys->load('simple_smileys', '/path/to/grav...') #2 /path/to/grav/user/plugins/smileys/smileys.php(237): Grav\Plugin\Smileys->__construct('simple_smileys', '/path/to/grav...') #3 /path/to/grav/user/plugins/smileys/smileys.php(113): Grav\Plugin\SmileysPlugin->init() #4 [internal function]: Grav\Plugin\SmileysPlugin->onPageContentProcessed(Object(RocketTheme\Toolbox\Event\Event), 'onPageContentPr...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #5 /path/to/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPageContentPr...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #6 /path/to/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageContentPr...', Object(RocketTheme\Toolbox\Event\Event)) #7 /path/to/grav/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageContentPr...', Object(RocketTheme\Toolbox\Event\Event)) #8 /path/to/grav/system/src/Grav/Common/Grav.php(272): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageContentPr...', Object(RocketTheme\Toolbox\Event\Event)) #9 /path/to/grav/system/src/Grav/Common/Page/Page.php(598): Grav\Common\Grav->fireEvent('onPageContentPr...', Object(RocketTheme\Toolbox\Event\Event)) #10 /path/to/grav/system/src/Grav/Common/Twig/Twig.php(319): Grav\Common\Page\Page->content() #11 /path/to/grav/system/src/Grav/Common/Service/OutputServiceProvider.php(18): Grav\Common\Twig\Twig->processSite(NULL) #12 /path/to/grav/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #13 /path/to/grav/system/src/Grav/Common/Processors/RenderProcessor.php(17): Pimple\Container->offsetGet('output') #14 /path/to/grav/system/src/Grav/Common/Grav.php(121): Grav\Common\Processors\RenderProcessor->process() #15 /path/to/grav/system/src/Grav/Common/Grav.php(358): Grav\Common\Grav->Grav\Common\{closure}() #16 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #17 /path/to/grav/system/src/Grav/Common/Grav.php(334): call_user_func_array(Object(Closure), Array) #18 /path/to/grav/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #19 /path/to/grav/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #20 /path/to/grav/index.php(45): Grav\Common\Grav->process() #21 {main} [] []
```

**Comment by daverdalas** [comment]
I had the same problem. From what I was able to figure the default pack of icons has a bad configuration file (not matching names for emojis files) instead of default package use this: Https://github.com/sommerregen/grav-data-smileys-emoji than in page content past those codes: http://www.webpagefx.com/tools/emoji-cheat-sheet/

**Comment by daverdalas** [comment]
Also look here: https://github.com/Sommerregen/grav-plugin-smileys/issues/3

**Comment by tmk1** [comment]
@daverdalas you're right - there are two mistakes on the list.

It's not visible if in php.ini: error_reporting is set to omit E_NOTICE errors.

**Comment by Heraes-git** [comment]
Same problem today. Here's the complete list of errors : 

```
Whoops\Exception\ErrorException thrown with message "Undefined index: enabled"

Stacktrace:
#20 Whoops\Exception\ErrorException in D:\Work\Programmation\Web\Tests\grav\www\user\plugins\smileys\classes\Smileys.php:202
#19 Whoops\Run:handleError in D:\Work\Programmation\Web\Tests\grav\www\user\plugins\smileys\classes\Smileys.php:202
#18 Grav\Plugin\Smileys:load in D:\Work\Programmation\Web\Tests\grav\www\user\plugins\smileys\classes\Smileys.php:80
#17 Grav\Plugin\Smileys:__construct in D:\Work\Programmation\Web\Tests\grav\www\user\plugins\smileys\smileys.php:237
#16 Grav\Plugin\SmileysPlugin:init in D:\Work\Programmation\Web\Tests\grav\www\user\plugins\smileys\smileys.php:113
#15 Grav\Plugin\SmileysPlugin:onPageContentProcessed in D:\Work\Programmation\Web\Tests\grav\www\vendor\symfony\event-dispatcher\EventDispatcher.php:184
#14 call_user_func in D:\Work\Programmation\Web\Tests\grav\www\vendor\symfony\event-dispatcher\EventDispatcher.php:184
#13 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in D:\Work\Programmation\Web\Tests\grav\www\vendor\symfony\event-dispatcher\EventDispatcher.php:46
#12 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in D:\Work\Programmation\Web\Tests\grav\www\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php:23
#11 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Grav.php:288
#10 Grav\Common\Grav:fireEvent in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Page\Page.php:668
#9 Grav\Common\Page\Page:content in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Twig\Twig.php:324
#8 Grav\Common\Twig\Twig:processSite in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Service\OutputServiceProvider.php:27
#7 Grav\Common\Service\OutputServiceProvider:Grav\Common\Service\{closure} in D:\Work\Programmation\Web\Tests\grav\www\vendor\pimple\pimple\src\Pimple\Container.php:118
#6 Pimple\Container:offsetGet in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Processors\RenderProcessor.php:19
#5 Grav\Common\Processors\RenderProcessor:process in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Grav.php:132
#4 Grav\Common\Grav:Grav\Common\{closure} in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Grav.php:379
#3 Grav\Common\Grav:Grav\Common\{closure} in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Grav.php:355
#2 call_user_func_array in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Grav.php:355
#1 Grav\Common\Grav:__call in D:\Work\Programmation\Web\Tests\grav\www\system\src\Grav\Common\Grav.php:133
#0 Grav\Common\Grav:process in D:\Work\Programmation\Web\Tests\grav\www\index.php:52
```
